# Generated by Django 3.0.2 on 2020-01-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.Status'),
        ),
    ]
