# Generated by Django 3.0.2 on 2020-01-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200128_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Status'),
        ),
    ]
